def menu():
    print("-"*50)
    print("Employee Information System")
    print("-"*50)
    print("\t1.Add New Employee")
    print("\t2.Delete Employee")
    print("\t3.Update Employee")
    print("\t4.View Employee Details")
    print("\t5.View All Employee Details")
    print("\t6.Search Employee Details")
    print("\t7.Exit")
    print("-"*50)
